name: eco_hero_mobile
description: 'Aplikacja motywująca do działań proekologicznych poprzez śledzenie śladu węglowego, wyzwania, gamifikację oraz integrację z IoT, wspierając zrównoważony styl życia i ochronę klimatu poprzez codzienne nawyki użytkowników'
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2


dependencies:
  flutter:
    sdk: flutter
  get_it: ^8.0.1
  equatable: ^2.0.5
  freezed: ^2.5.7
  google_fonts: ^6.2.1
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  go_router: ^14.3.0
  dio: ^5.7.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  either_dart: ^1.0.0
  responsive_sizer: ^3.3.1
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  carousel_slider: ^5.0.0
  flutter_markdown: ^0.7.4+1
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/raleway/Raleway-ExtraLight.ttf
          weight: 200
        - asset: fonts/raleway/Raleway-Light.ttf
          weight: 300
        - asset: fonts/raleway/Raleway-Regular.ttf
          weight: 400
        - asset: fonts/raleway/Raleway-Medium.ttf
          weight: 500
        - asset: fonts/raleway/Raleway-SemiBold.ttf
          weight: 600
        - asset: fonts/raleway/Raleway-Bold.ttf
          weight: 700
        - asset: fonts/raleway/Raleway-ExtraBold.ttf
          weight: 800
        - asset: fonts/raleway/Raleway-Black.ttf
          weight: 900